title: "Damien Marion"
logo: /assets/img/picture_dma.jpg
# email: damien.marion {at} gmail.com // damien.marion {at} irisa.fr
# blank_title: true
favicon: false
description: "Side-Channel researcher at Univ Rennes, CNRS, Inria, IRISA
Rennes, France."
show_downloads: false
google_analytics: G-X6T51CN3BH
theme: jekyll-theme-minimalist
color-scheme: dark
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jemoji
  - 'jekyll/scholar'
  - jekyll-last-modified-at

# Optional. The default date format, used if none is specified in the tag.
## try
last-modified-at:
  date-format: '%d-%b-%y'

scholar:
  last_name: Marion

  style: apa
  locale: en

  sort_by: year
  order: descending

  group_by: none
  group_order: ascending

  source: ./_bibliography
  bibliography: references.bib
  bibliography_template: bibtemplate

  replace_strings: true
  join_strings:    true

  # use_raw_bibtex_entry: true

  details_dir:    bibliography
  details_layout: bibtex.html
  details_link:   Details

  query: "@*"
